protected/modules/admin/controllers/FeaturesController.php
<?php

class FeaturesController extends BaseAdminController {

	/**
	 * @return array action filters
	 */
	public function filters() {
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	public function actionIndex() {
		$this->pageName = 'Features';
		$model = StaticPage::model()->findByAttributes(array('page_id' => 'features'));
		if (!isset($model)) {
			$model = new StaticPage();
		}
		$model->page_id = 'features';
		// if it is ajax validation request
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'features-form') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
		if (isset($_POST['StaticPage'])) {
			$model->setAttributes($_POST['StaticPage']);
			$model->updated = date('Y-m-d H:i:s', time());
			if ($model->save()) {
				Yii::app()->user->setFlash('success', "Update successfully!");
			}
		}
		$this->render('index', array('model' => $model));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate() {
		$this->pageName = 'Create Feature';
		$model = new Features;

		//Default always show in front end
		$model->show = 1;

		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);

		if (isset($_POST['Features'])) {
			$model->attributes = $_POST['Features'];
			if (!$model->order_position) {
				$model->order_position = 0;
			}
			$model->image = CUploadedFile::getInstance($model, 'image');
			if ($model->validate()) {
				//Dont worry about duplicate upload image when validate model many time, because validate ajax frist
				$fileName = Uploader::uploadImage($model, CfConst::IMG_DIR_FEATURES);
				$model->image = $fileName;
			}
			if ($model->save()) {
				$this->redirect(array('admin'));
			}
		}

		$this->render('create', array(
			'model' => $model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id) {
		$this->pageName = 'Update Feature';
		$model = $this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);

		if (isset($_POST['Features'])) {
			$model->attributes = $_POST['Features'];
			if (!$model->order_position) {
				$model->order_position = 0;
			}
			if ($model->validate()) {
				//Dont worry about duplicate upload image when validate model many time, because validate ajax frist
				//In edit action, put old image name to function to remove old image, if new image uploaded
				$fileName = Uploader::uploadImage($model, CfConst::IMG_DIR_FEATURES, $model->image);
				$model->image = $fileName;
			}
			if ($model->save()) {
				$this->redirect(array('admin'));
			}
		}

		$this->render('update', array(
			'model' => $model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id) {
		$model = $this->loadModel($id);
		//Remove image and thumb
		Uploader::removeImage(CfConst::IMG_DIR_FEATURES, $model->image);
		$model->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if (!isset($_GET['ajax'])) {
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
	}

	public function actionDeletes() {
		if (isset($_POST['theIds'])) {
			$IDs = explode(',', $_POST['theIds']);
			foreach ($IDs as $id) {
				$model = $this->loadModel($id, 'Features');
				//Remove image and thumb
				Uploader::removeImage(CfConst::IMG_DIR_FEATURES, $model->image);
				$model->delete();
			}
			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if (!isset($_GET['ajax'])) {
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
			}
		}
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin() {
		$this->pageName = 'Manage Features';
		$model = new Features('search');
		$model->unsetAttributes();  // clear any default values
		if (isset($_GET['Features'])) {
			$model->attributes = $_GET['Features'];
		}

		$this->render('admin', array(
			'model' => $model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Features the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id) {
		$model = Features::model()->findByPk($id);
		if ($model === null) {
			throw new CHttpException(404, 'The requested page does not exist.');
		}
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Features $model the model to be validated
	 */
	protected function performAjaxValidation($model) {
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'features-form') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

}

protected/modules/admin/views/features/_form.php
<script src="<?php echo REL_BASE_URL; ?>/ckeditor/ckeditor.js"></script>
<?php 
	$form = $this->beginWidget('CActiveForm', array(
		'id'=>'features-form',
		'enableClientValidation'=>true,
		//'enableAjaxValidation'=>true, DOESNT NEED AJAX IN FORM HAS UPLOAD FILE FIELD
		'errorMessageCssClass'=>'alert alert-danger', //alert alert-error
		'clientOptions'=>array(
			'validateOnSubmit'=>true,
			'validateOnType'=>false,
			'validateOnChange'=>false,
			'successCssClass' => 'has-success',
			'errorCssClass' => 'has-error',
			'afterValidate' => 'js:function(form){$("#sucess_msg").remove(); return true;}'//Remove success message if it have, return true to continue validate
		),
		'htmlOptions' => array(
			'onSubmit' => 'saveCkEditor()',//Define in ckeditor config.js
			'enctype' => 'multipart/form-data', // For upload image
		),
	)); 
?>

	<?php if( $msg = Yii::app()->user->getFlash('success') ) : ?>
		<div id="sucess_msg" class="alert alert-success"><?php echo $msg; ?></div>
	<?php endif;?>
	<?php echo $form->error($model,'name'); ?>
	<?php echo $form->error($model,'description'); ?>
	<?php echo $form->error($model,'image'); ?>
	<?php echo $form->error($model,'order_position'); ?>
	<?php echo $form->error($model,'show'); ?>

	<div class="form-group">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('maxlength'=>255, 'class' => 'form-control')); ?>
	</div>

	<div class="form-group">
		<?php echo $form->labelEx($model,'description'); ?>
		<?php echo $form->textArea($model,'description',array('class' => 'ckeditor')); ?>
	</div>
		
	<div class="form-group">
		<?php echo $form->labelEx($model,'image'); ?>
		<div class="checkbox" style="display: inline;">
			<label>
				<?php echo $form->fileField($model, 'image'); ?> 
			</label>
		</div>
	</div>
		
	<div class="form-group">
		<?php if($model->isNewRecord!='1' && $model->image): ?>
			<?php echo CHtml::image(CfConst::IMG_DIR_FEATURES.CfConst::THUMB_FOLDER_NAME.CfConst::THUMB_IMG_PREFIX_NAME.$model->image,"image"); ?>
		<?php endif;?>
	</div>
		
	<div class="form-group">
		<?php echo $form->labelEx($model,'order_position'); ?>
		<?php echo $form->textField($model,'order_position', array('class' => 'form-control')); ?>
	</div>
		
	<div class="form-group">
		<?php echo $form->labelEx($model,'show'); ?>
		<div class="checkbox" style="display: inline;">
			<label>
				<?php echo $form->checkBox($model, 'show'); ?>
			</label>
		</div>    
	</div>
		
	<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save', array('class' => 'btn btn-primary btn-send-t margin-sm-top')); ?>

<?php $this->endWidget(); ?>

<script type="text/javascript">
//Override height
CKEDITOR.replace('Features_description', {
	height: 300,
});
</script>

protected/modules/admin/views/features/_search.php
<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<div class="col-md-6">
			<div class="form-group input-group">
				<span class="input-group-addon">Name</span>
				<?php echo $form->textField($model,'name',array('maxlength'=>500, 'class'=>'form-control')); ?>
			</div>
		</div>
		<div class="col-md-1">
			<button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
		</div>
	</div>
<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/modules/admin/views/features/admin.php
<?php

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#features-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				List Features
			</div>
			<!-- /.panel-heading -->
			<div class="panel-body">
				<div class="row">
					<div class="search-form col-lg-6">
					<?php $this->renderPartial('_search',array(
						'model'=>$model,
					)); ?>
					</div><!-- search-form -->				
					<div class="table-responsive col-lg-12">
						<div>
							<?php
							echo CHtml::link('Create new Feature',array('features/create'), array('class'=>'btn btn-primary'));
							?>			
							<?php
							echo CHtml::ajaxLink(
								'Delete Feature(s)', $this->createUrl('features/deletes'), 
								array(
									'type' => 'POST',
									'data' => 'js:{theIds : $.fn.yiiGridView.getChecked("features-grid","feature-check-boxes").toString()}',
									'success' => 'function( data )
										{
											$("#features-grid").yiiGridView.update("features-grid");
										}',
									'error' => 'function(data) { alert("error"); }',
								), 
								array(
									'confirm' => Yii::t('app', 'Are you sure you want to delete Feature(s)?'),
									'class' => 'ajaxDelete btn btn-danger',
								)
							);
							?>
						</div>	
						<?php $this->widget('zii.widgets.grid.CGridView', array(
							'id'=>'features-grid',
							'htmlOptions'=>array(
							),
							//'ajaxUpdate'=>false, 
							'enableSorting'=>false,
							'filterPosition'=>'none', // Hide filter
							'itemsCssClass' => 'table table-striped table-bordered table-hover', //Add class css for table
							'dataProvider'=>$model->search(),
							'filter'=>$model,
							'columns'=>array(
								array(
									'class'=>'CCheckBoxColumn',
									'header'=>'Selected',
									'id'=>'feature-check-boxes',
									'selectableRows' => 2,
									'checkBoxHtmlOptions'=>array('class'=>'feature_id'),//for js bottom of page
								),
								'id',
								'name',
								array(
									'name' => 'image',
									'type' => 'html',
									'value' => 'CHtml::image(CfConst::IMG_DIR_FEATURES.CfConst::THUMB_FOLDER_NAME.CfConst::THUMB_IMG_PREFIX_NAME.$data["image"],"image");',
								),
								'order_position',
								array(
									'name' => 'show',
									'value' => '$data["show"]==1?"Yes":"No"',
								),
								array(
									'class'=>'CButtonColumn',
									'template'=>'{update}{delete}',
									'deleteButtonImageUrl'=>false,
									'updateButtonImageUrl'=>false,
									'buttons'=>array(
										'update' => array(
											'options'=>array('class'=>'fa fa-pencil', 'target'=>'_blank', 'rel' => 'tooltip', 'data-toggle' => 'tooltip', 'title' => 'Upđate'),
											'label'=>''
										),
										'delete' => array(
											'options'=>array('class'=>'fa fa-times', 'rel' => 'tooltip', 'data-toggle' => 'tooltip', 'title' => 'Delete'),
											'label'=>''
										),
									),
								),
							),
							'pager'=>array(
								'htmlOptions'=>array('class'=>'pagination'),
								'class'=>'CLinkPager',
								//'cssFile'=>false,
								//'firstPageLabel'=>'First',
								//'lastPageLabel'=>'Last',
								'nextPageLabel'=>'Next',
								'prevPageLabel'=>'Previous',
								'selectedPageCssClass'=>'active',
								'hiddenPageCssClass'=>'disabled',
								'header'=>'',
							),
						)); ?>
					</div>
					<!-- /.table-responsive -->
				</div>
			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->
	</div>
	<!-- /.col-lg-12 -->
</div>
<?php
	Yii::app()->clientScript->registerScript('check-form', "
		$('.ajaxDelete').click(function (){
			if($('.feature_id:checkbox:checked').length > 0){
				return true;
			}else {
				alert('You must select at least one item to do this action.');
				return false;
			}
		});
		return true;
	", CClientScript::POS_READY);
 ?>

protected/modules/admin/views/features/create.php
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				Create Feature
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-lg-9">
						<?php $this->renderPartial('_form', array('model'=>$model)); ?>
					</div>
					<!-- /.col-lg-6 (nested) -->
				</div>
				<!-- /.row (nested) -->
			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->
	</div>
	<!-- /.col-lg-12 -->
</div>

protected/modules/admin/views/features/index.php
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				Update Overview Features
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-lg-9">
						<?php 
							$form = $this->beginWidget('CActiveForm', array(
								'id'=>'features-form',
								'enableClientValidation'=>false,
								'enableAjaxValidation'=>true,
								'errorMessageCssClass'=>'alert alert-danger', //alert alert-error
								'clientOptions'=>array(
									'validateOnSubmit'=>true,
									'validateOnType'=>false,
									'validateOnChange'=>false,
									'successCssClass' => 'has-success',
									'errorCssClass' => 'has-error',
									'afterValidate' => 'js:function(form){$("#sucess_msg").remove(); return true;}'//Remove success message if it have, return true to continue validate
								),
								'htmlOptions' => array(
									'onSubmit' => '',//Define in ckeditor config.js
								),
							)); 
						?>
							
							<?php if( $msg = Yii::app()->user->getFlash('success') ) : ?>
								<div id="sucess_msg" class="alert alert-success"><?php echo $msg; ?></div>
							<?php endif;?>
							<?php echo $form->error($model, 'name'); ?>
							<?php echo $form->error($model, 'description'); ?>
							
							<div class="form-group">
								<?php echo $form->labelEx($model, 'name'); ?>
								<?php echo $form->textField($model, 'name', array('maxlength' => 255, 'class' => 'form-control')); ?>	
							</div>
						
							<div class="form-group">
								<?php echo $form->labelEx($model, 'description'); ?>
								<?php echo $form->textField($model, 'description', array('maxlength' => 1000, 'class' => 'form-control')); ?>
							</div>
						
							<?php echo CHtml::submitButton('Save', array('class' => 'btn btn-primary btn-send-t margin-sm-top')); ?>
						
						<?php $this->endWidget(); ?>
					</div>
					<!-- /.col-lg-6 (nested) -->
				</div>
				<!-- /.row (nested) -->
			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->
	</div>
	<!-- /.col-lg-12 -->
</div>

protected/modules/admin/views/features/update.php
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				Update Feature
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-lg-9">
						<?php $this->renderPartial('_form', array('model'=>$model)); ?>
					</div>
					<!-- /.col-lg-6 (nested) -->
				</div>
				<!-- /.row (nested) -->
			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->
	</div>
	<!-- /.col-lg-12 -->
</div>